version: '3' # docker-compose -f ./docker-compose.dev.yml

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - "NODE_ENV=development"
    container_name: next