export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;


export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;

export const LAYOUT_SLIDER_SHOW = 'LAYOUT_SLIDER_SHOW';
export type LAYOUT_SLIDER_SHOW = typeof LAYOUT_SLIDER_SHOW;

export const LAYOUT_SLIDER_HIDE = 'LAYOUT_SLIDER_HIDE';
export type LAYOUT_SLIDER_HIDE = typeof LAYOUT_SLIDER_HIDE;