export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;


/**
 * layout header slider toggle
 */
// export const LAYOUT_SLIDER_COLLAPSED_SHOW = 'LAYOUT_SLIDER_COLLAPSED_SHOW';
// export type LAYOUT_SLIDER_COLLAPSED_SHOW = typeof LAYOUT_SLIDER_COLLAPSED_SHOW;

// export const LAYOUT_SLIDER_COLLAPSED_HIDE = 'LAYOUT_SLIDER_COLLAPSED_HIDE';
// export type LAYOUT_SLIDER_COLLAPSED_HIDE = typeof LAYOUT_SLIDER_COLLAPSED_HIDE;

export const SLIDERBAR_SHOW = 'SLIDERBAR_SHOW';
export type SLIDERBAR_SHOW = typeof SLIDERBAR_SHOW;

export const SLIDERBAR_HIDE = 'SLIDERBAR_HIDE';
export type SLIDERBAR_HIDE = typeof SLIDERBAR_HIDE;