export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;


/**
 * layout header slider toggle
 */
export const LAYOUT_SLIDER_COLLAPSED_SHOW = 'LAYOUT_SLIDER_COLLAPSED_SHOW';
export type LAYOUT_SLIDER_COLLAPSED_SHOW = typeof LAYOUT_SLIDER_COLLAPSED_SHOW;

export const LAYOUT_SLIDER_COLLAPSED_HIDE = 'LAYOUT_SLIDER_COLLAPSED_HIDE';
export type LAYOUT_SLIDER_COLLAPSED_HIDE = typeof LAYOUT_SLIDER_COLLAPSED_HIDE;